name: Testing
on: push

jobs:
  test_project:
    runs-on: ubunthu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip 3 install --user django
        python3 manage.py test
